
services:
  nextjs:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # volumes:
    #   - .:/src
    networks:
      - cs_network


networks:
  cs_network:
    external: true