import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar";
import '@mantine/core/styles.css';
import { createTheme, MantineProvider } from '@mantine/core';
import { AppWrapper } from "../context";

const theme = createTheme({});


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AppWrapper>
          <MantineProvider theme={theme}>
            <Navbar/>
              {children}
          </MantineProvider>
        </AppWrapper>
      </body>
    </html>
  );
}
